// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jbdvrnorjvhtqehoexfw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpiZHZybm9yanZodHFlaG9leGZ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5NjkxNDYsImV4cCI6MjA2OTU0NTE0Nn0.O2FcogBRPYbcK0OL8P0NQfcdEdl7TjbLbw7bDMVVZY0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});